### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [Hdoc1509/shell-fns#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by Hdoc1509** [comment]
Hi, unixorn.
Yep, I forgot the License. My bad. I'll add it as soon as possible.
